Update spec file to work with aarch84 targets
llewelld/harbour-contrac pull request #100
Opened 2021-06-02 20:35 UTC by llewelld

2021-06-02 21:44 UTC, llewelld commented
Rebased.

2021-06-03 09:22 UTC, bionade24 approved these changes

2021-06-09 11:45 UTC, bionade24 requested changes

2021-06-09 11:45 UTC, bionade24 commented on rpm/harbour-contrac.spec
> +%{_userunitdir}/contracd.service
Doesn't this also need a change here? https://github.com/llewelld/harbour-contrac/blob/25b36142001bb1880f6bd71f8c6734f1ca1f0836/contracd/contracd.pro#L92

2021-06-09 11:49 UTC, bionade24 commented on rpm/harbour-contrac.spec
> +%{_userunitdir}/contracd.service
Nevermind it's fine, I overlooked the `/user/` and got confused.

2021-06-09 11:49 UTC, bionade24 approved these changes

2021-12-30 22:12 UTC, merged

2021-12-30 22:12 UTC, bionade24 commented
I'm doing merge commits for now. @llewelld please tell if you would like to switch to only rebase PRs on master.